spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/subway_map
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:masterpw}

spring.jpa.properties.hibernate.show_sql=false